"""Extract visible body text from every case-study-*.html and write search-index.js.

Run this whenever an article's text content changes, so the homepage search
(index.html) can match on real body keywords, not just each card's short alt text.
"""
import glob
import json
import os
import re
from html.parser import HTMLParser

SITE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SKIP_TAGS = {"script", "style", "nav", "footer"}
SKIP_IDS = {"videoLightbox"}


def _is_trigger(tag, attrs):
    if tag in SKIP_TAGS:
        return True
    attrs = dict(attrs)
    classes = attrs.get("class", "")
    if "other-work" in classes:
        return True
    if attrs.get("id") in SKIP_IDS:
        return True
    return False


class TextExtractor(HTMLParser):
    """Extracts visible body text, excluding nav/footer/other-work/video-modal
    boilerplate that would otherwise pollute the search index with other
    articles' titles (every page's Other Work section links to ~2 others)."""

    def __init__(self):
        super().__init__()
        self.chunks = []
        self.trigger_stack = []

    def handle_starttag(self, tag, attrs):
        if _is_trigger(tag, attrs):
            self.trigger_stack.append(tag)

    def handle_endtag(self, tag):
        if self.trigger_stack and self.trigger_stack[-1] == tag:
            self.trigger_stack.pop()

    def handle_data(self, data):
        if not self.trigger_stack:
            self.chunks.append(data)

    def text(self):
        return " ".join(self.chunks)


def extract_text(html_path):
    with open(html_path, encoding="utf-8") as f:
        html = f.read()
    parser = TextExtractor()
    parser.feed(html)
    raw = parser.text().lower()
    raw = re.sub(r"\s+", " ", raw).strip()
    return raw


def main():
    index = {}
    for path in sorted(glob.glob(os.path.join(SITE_ROOT, "case-study-*.html"))):
        filename = os.path.basename(path)
        index[filename] = extract_text(path)

    out_path = os.path.join(SITE_ROOT, "search-index.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/build_search_index.py — do not hand-edit.\n")
        f.write("// Regenerate after any article text change.\n")
        f.write("window.CASE_SEARCH_INDEX = ")
        f.write(json.dumps(index, ensure_ascii=False))
        f.write(";\n")

    total_kb = os.path.getsize(out_path) / 1024
    print(f"Wrote {out_path} ({total_kb:.1f} KB, {len(index)} articles)")


if __name__ == "__main__":
    main()
